In [1]:
import numpy as np
import pandas as pd
import ee
import geemap
import os
import glob

In [2]:
ee.Authenticate()
ee.Initialize(project = "ee-sarice")

In [3]:
# load cci lake points
cci_lakes = ee.FeatureCollection("projects/ee-sarice/assets/CCI_Lakes")

In [4]:
# CCI lake ids
cci_lake_ids = cci_lakes.aggregate_array("CCI ID").getInfo()

In [5]:
years = list(range(2000, 2024))

In [6]:
out_dir = "/mnt/Data_2tb/laketemp_bias/modis_cloud/raw"

In [7]:
for yr in years:
    # Load MODIS LST
    modis_lst = ee.ImageCollection("MODIS/061/MOD11A1").select("LST_Day_1km").filterDate(f"{yr}-01-01", f"{yr+1}-01-01")
    # extract modis lst
    geemap.zonal_statistics(modis_lst.toBands(),
                        cci_lakes,
                        f"{out_dir}/{yr}_terra_lst.csv", # should be total pixels.csv
                        statistics_type='MEAN',
                        scale = 1000,
                       )

Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/66b796e9be761ad0f39a93319781f449-69180352e8fae48f4d9586dea403196b:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2000_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/4114d9242722acfadd5f68d90190e736-27506213c06a3b454e68436ad8af9e80:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2001_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/c53b920bc582851703c6966e1239d120-015dc83382a4738121b58c74dd7f6d93:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2002_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/40218a08e3f9c8e020c7cfe6d5c6b4eb-24baac69d46e8354c2613bb0ef485219:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2003_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/6ea6d3f8892b38ae60adfe1b4574c652-a44724cf3b6aa9fc5e3cb379bddf3936:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2004_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/bdc12b21dafb6150480e98ee918c3722-c6933610229753bb88ff47c96c509b8c:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2005_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/8c8df91fd64517e608d847b8111c7f50-66dec896e2912ddf7144e2624289fc86:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2006_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/41b52ae2dd6f4502a8225e4fbb5d2681-cb5d5481260dbbeb876de789e39f4ce6:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2007_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/814dadc830db15f626f159e63c789526-1f9badd081821170383c49a12a44df71:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2008_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/ccc473425dd90b28810a92c9efc4fd83-c4604db9a9887b595582fe82ab07293c:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2009_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/5ab413b9393a72f472b253ac0e013bfc-ca8d0cf27e688cd74a9b8e1f9cc5064c:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2010_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/d393763ec3b9172d5496d90b1cf6204f-ddf649b0bc1b14924c71d0ff470d6d34:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2011_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/4c39045c5b3ae8aca948af2edf1c6d33-0c904d2da113ed232c1d16aa789cdb7f:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2012_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/4142b3fd49792ae237dd0dab6799b4e6-4ba374fddf61bc3355164f0a89ddd523:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2013_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/09fdc4c65dd8ed4bfdc6af22669fb010-e21215cfa8bcefecbf218e6861f6a87d:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2014_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/bf264b832acc59d605cb01508f7450cb-fe4af4ef024a1e3d86642439f7089114:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2015_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/8e9fb288759f11cbdda8ac553a3ef7ca-706597309bbcc5e5c63a31f38aed7291:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2016_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/8f81d37ec713424c7f5b25e54bdd0869-d230fba74e7c34ce478f16fc6db81e07:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2017_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/6f26a7287d71b4afac3e36a16c9d7d13-d900ebd0275b304767491c61ff246a2e:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2018_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/52367985761236094a9f746ad83e5408-1bbecf2bb5cf48d9bf0b45fec29aa04d:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2019_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/aa685c1ce081b568ee27cfe364fa09a8-a63f9d53a0092d14d950b09b335f53d5:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2020_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/5e6926e91ba7336ac8bae9170158441c-87cbdd099110c1e5e441a3883e82171d:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2021_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/6e8c24b0ab739ace52cac44bcdd7323f-3e3e27167bf6c23f46450ab2f698885b:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2022_terra_lst.csv
Computing statistics ...
Generating URL ...
Downloading data from https://earthengine.googleapis.com/v1/projects/ee-sarice/tables/e2cfd2c0bfd1b5f6790d1050aa4837a2-d467090d00d891d5a7cce3ea7e0e330b:getFeatures
Please wait ...
Data downloaded to /mnt/Data_2tb/laketemp_bias/modis_cloud/raw/2023_terra_lst.csv

# Merge to one dataframe

In [8]:
import numpy as np
import pandas as pd
import os
import glob

In [2]:
# out_dir = "/mnt/Data_2tb/laketemp_bias/modis_cloud/raw"
out_dir = "/nas/cee-hydro/laketemp_bias/modis_cloud/raw"

In [3]:
cloud_cover_df = pd.DataFrame([])

for yr in list(range(2000, 2024)):
    # read the raw file
    df_lst = pd.read_csv(f"{out_dir}/{yr}_terra_lst.csv",).set_index("CCI ID").iloc[:, :-10]
    # if na, then it is cloud cover
    df_cloud_cover = df_lst.isna()
    df_cloud_cover.columns = pd.to_datetime([col.replace("_LST_Day_1km", "") for col in df_cloud_cover.columns], format = "%Y_%m_%d")
    df_cloud_cover = df_cloud_cover.T
    df_cloud_cover.columns.name = ""
    df_cloud_cover.index.name = "date"
    cloud_cover_df = pd.concat([cloud_cover_df, df_cloud_cover], axis = 0)

# set column names to str 
cloud_cover_df.columns = cloud_cover_df.columns.astype(str)
# True means cloudy, False means not cloudy
cloud_cover_df

,799,3114,7889,2516,12262,1519,3053,1203,3350,3607,...,278,293,300000771,378,317,473,309,141,212,170
date,,,,,,,,,,,,,,,,,,,,,
2000-02-24,True,True,True,True,True,True,True,True,True,True,...,False,True,False,True,True,True,True,True,True,True
2000-02-25,True,True,True,True,False,False,True,True,True,False,...,False,True,True,True,True,True,False,True,True,True
2000-02-26,False,True,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,True,True
2000-02-27,True,True,True,True,True,True,True,False,False,True,...,True,True,True,True,True,True,True,True,False,True
2000-02-28,False,False,True,True,True,False,True,True,True,True,...,True,True,True,True,True,True,True,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-27,False,True,True,True,True,True,True,False,False,False,...,True,True,True,True,True,True,True,True,True,True
2023-12-28,True,True,False,True,True,False,True,False,False,False,...,False,True,True,False,True,True,False,True,False,True
2023-12-29,True,False,True,False,True,False,True,False,False,False,...,True,True,True,False,True,True,False,True,False,True
2023-12-30,False,True,False,True,True,True,True,False,True,False,...,False,True,True,True,True,True,True,True,False,True
2023-12-31,True,True,True,True,False,False,True,True,True,False,...,False,True,False,False,True,True,False,True,False,True

# Mask out cloudy days

In [5]:
water_temp_df = pd.read_csv("/nas/cee-hydro/laketemp_bias/era5land/water_temp.csv", index_col=0, parse_dates=True)

In [6]:
# keep the non-cloudy observations
temp_df = water_temp_df.mask(cloud_cover_df, np.nan)
temp_df.loc[pd.date_range("2020-07-01", "2020-07-31"), "62"]

2020-07-01          NaN
2020-07-02          NaN
2020-07-03          NaN
2020-07-04    10.918571
2020-07-05          NaN
2020-07-06          NaN
2020-07-07          NaN
2020-07-08          NaN
2020-07-09          NaN
2020-07-10    10.666950
2020-07-11    11.385794
2020-07-12          NaN
2020-07-13    12.507469
2020-07-14    13.122165
2020-07-15          NaN
2020-07-16    13.381817
2020-07-17    14.801996
2020-07-18    14.255700
2020-07-19          NaN
2020-07-20          NaN
2020-07-21          NaN
2020-07-22          NaN
2020-07-23          NaN
2020-07-24          NaN
2020-07-25          NaN
2020-07-26    14.268321
2020-07-27    13.085286
2020-07-28    14.051697
2020-07-29    13.128550
2020-07-30          NaN
2020-07-31          NaN
Name: 62, dtype: float64

In [7]:
water_temp_df_cloud = water_temp_df.mask(cloud_cover_df, np.nan)
water_temp_df_cloud.to_csv("/nas/cee-hydro/laketemp_bias/era5land/water_temp_cloud.csv")

In [9]:
water_temp_df_cloud

,799,3114,7889,2516,12262,1519,3053,1203,3350,3607,...,300000430,278,293,300000771,378,473,309,141,212,170
2000-01-01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-04,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2000-01-05,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2023-12-27,15.396758,NaN,NaN,NaN,NaN,NaN,NaN,4.061035,3.459507,21.349592,...,-0.000342,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2023-12-28,NaN,NaN,6.700112,NaN,NaN,7.396017,NaN,4.053041,3.504207,21.951714,...,-0.000342,6.988318,NaN,NaN,2.999573,NaN,0.752726,NaN,-0.000342,NaN
2023-12-29,NaN,3.617657,NaN,4.023334,NaN,6.898298,NaN,3.977074,4.106709,22.446399,...,-0.000342,NaN,NaN,NaN,2.998324,NaN,0.720556,NaN,-0.000342,NaN
2023-12-30,15.608841,NaN,5.829605,NaN,NaN,NaN,NaN,3.873746,NaN,22.942908,...,NaN,7.067787,NaN,NaN,NaN,NaN,NaN,NaN,-0.000342,NaN
2023-12-31,NaN,NaN,NaN,NaN,2.593807,6.401340,NaN,NaN,NaN,23.497687,...,-0.000342,7.025704,NaN,0.828416,2.898258,NaN,0.650813,NaN,-0.000342,NaN